"""GENERATED by frontend/scripts/build-tokens.ts -- do not hand-edit.

Mirrors frontend/src/tokens/tokens.ts (the one token source, spec 03.4)
for the textual TUI so both renderers share one design vocabulary.
"""

from __future__ import annotations

SPACE: dict[str, str] = {
    "0": "0px",
    "1": "4px",
    "2": "8px",
    "3": "12px",
    "4": "16px",
    "5": "20px",
    "6": "24px",
    "8": "32px",
    "10": "40px",
    "12": "48px",
    "16": "64px",
}

RADIUS: dict[str, str] = {
    "none": "0px",
    "sm": "2px",
}

FONT_SIZE: dict[str, str] = {
    "11": "11px",
    "12": "12px",
    "13": "13px",
    "14": "14px",
    "16": "16px",
    "20": "20px",
}

COLOR_DARK: dict[str, str] = {
    "paper": "#111417",
    "raised": "#171B1F",
    "ink": "#D7DEE4",
    "inkDim": "#8A949D",
    "hairline": "#2A3138",
    "accent": "#E8A33D",
    "verdict.discharged": "#4CAF6E",
    "verdict.violated": "#E05252",
    "verdict.deferred": "#D9B23D",
    "verdict.acceptedDeviation": "#7A8CE0",
    "verdict.excluded": "#8A949D",
}

COLOR_LIGHT: dict[str, str] = {
    "paper": "#F4F2EC",
    "raised": "#FFFFFF",
    "ink": "#1A1D20",
    "inkDim": "#5B6167",
    "hairline": "#C9C4B8",
    "accent": "#8A5A16",
    "verdict.discharged": "#2F7D4C",
    "verdict.violated": "#B23A3A",
    "verdict.deferred": "#7D5F14",
    "verdict.acceptedDeviation": "#4B57A8",
    "verdict.excluded": "#5A5F67",
}
