/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/config/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Config Schema
         * @description Every registered key's default/kind/doc, global and static (not
         *     per-project) -- the "reset to default" affordance's data source
         *     since neither `config list` nor `where` prints a default.
         */
        get: operations["get_config_schema_api_config_schema_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ping
         * @description Liveness probe (not a lithos health report -- see
         *     `/api/projects/{project}/health` for that).
         */
        get: operations["ping_api_ping_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Projects
         * @description Every project under the server's configured scan root
         *     (04.1 "ANY TABLE" floor: the frontend adds sort/filter/count over
         *     this listing -- the route itself stays a plain array, no
         *     server-side pagination needed at fleet scale).
         */
        get: operations["list_projects_api_projects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Project
         * @description One project's manifest identity + artifact presence flags.
         */
        get: operations["get_project_api_projects__project__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/acceptance-ledger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Acceptance Ledger
         * @description The accepted-deviation ledger (waiver/memo panel, project-view
         *     deliverable 2): every accepted deviation with its memo evidence
         *     digest and basis text, read verbatim (WOG1-F3 provisional bridge).
         */
        get: operations["get_acceptance_ledger_api_projects__project__acceptance_ledger_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Project Artifacts
         * @description Every artifact under the project's `dist/` (GLB/SVG/PDF/STEP/
         *     JSON alike), each entry naming its content hash -- the only valid
         *     fetch key (04.1 "ANY GRAPHIC" floor: content-hash caption).
         */
        get: operations["list_project_artifacts_api_projects__project__artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/artifacts/{content_hash}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch Project Artifact
         * @description Raw bytes for one artifact, looked up by content hash ONLY --
         *     `content_hash` must equal an entry this project's own listing
         *     produced; anything else is a 404, never a filesystem read of an
         *     arbitrary path.
         */
        get: operations["fetch_project_artifact_api_projects__project__artifacts__content_hash__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/build-report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Build Report
         * @description The full staged build report, including the BOM/cost/schedule
         *     fields (`cost_profile`, `cost_record_pins`, `cost_estimates`,
         *     `frame_lock_rows`) verbatim from regolith -- no local recomputation
         *     (charter sec. 3.2).
         */
        get: operations["get_build_report_api_projects__project__build_report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/calc/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Audit Index
         * @description The project's audit index (summary + rows) -- the same model
         *     `/obligations` filters/groups, exposed here unfiltered for a raw
         *     view (04.1 "ANY DETAIL VIEW" floor: raw-JSON toggle).
         */
        get: operations["get_audit_index_api_projects__project__calc_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/calc/sheets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Calc Sheets
         * @description Every calc sheet in the project's shipped calc book (04.1 "ANY
         *     TABLE" floor: sort/filter/CSV-export are frontend concerns over
         *     this same array, not a server-side feature).
         */
        get: operations["list_calc_sheets_api_projects__project__calc_sheets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Project Config
         * @description Every registered config key with its effective value + source.
         */
        get: operations["list_project_config_api_projects__project__config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/config/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Project Config
         * @description One key's effective value + winning source.
         */
        get: operations["get_project_config_api_projects__project__config__key__get"];
        /**
         * Set Project Config
         * @description Write one key through the real `regolith config set` (never a
         *     raw file poke).
         */
        put: operations["set_project_config_api_projects__project__config__key__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/doctor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Doctor
         * @description Every registered optional external tool's found/missing status
         *     (regolith's own report -- graphite renders it verbatim, per the
         *     read-mostly honesty posture).
         */
        get: operations["get_doctor_api_projects__project__doctor_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/gate-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Gate Summary
         * @description The release-gate summary panel (WOG3-F1, provisional bridge --
         *     project-view deliverable 2).
         */
        get: operations["get_gate_summary_api_projects__project__gate_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Project Health
         * @description `release_ok` from the build report + the audit index's obligation
         *     accounting -- both read verbatim, never recomputed.
         */
        get: operations["get_project_health_api_projects__project__health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/lockfile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Lockfile
         * @description The resolved `regolith.lock` (every pinned slot + its cause).
         */
        get: operations["get_lockfile_api_projects__project__lockfile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Manifest
         * @description The ship package manifest summary (WOG1-F2, provisional bridge).
         */
        get: operations["get_manifest_api_projects__project__manifest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/obligations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Obligations
         * @description The project's obligation rows, optionally filtered by disposition
         *     and/or grouped by disposition or claim family.
         */
        get: operations["get_obligations_api_projects__project__obligations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Project Runs
         * @description This project's run history, newest first.
         */
        get: operations["list_project_runs_api_projects__project__runs_get"];
        put?: never;
        /**
         * Start Project Run
         * @description Start `regolith <verb> <args>` against `project`'s root; returns
         *     immediately with a `running` record (04.1 "ANY LONG OPERATION"
         *     floor: a durable record + elapsed time via `started_at` for the
         *     frontend to compute).
         */
        post: operations["start_project_run_api_projects__project__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run Detail
         * @description One run's current record (re-polls liveness when still `running`,
         *     see `graphite.service.runs.get_run`).
         */
        get: operations["get_run_detail_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run Events
         * @description SSE stream of `run_id`'s log lines, closing with a `done` event
         *     once the run finishes.
         */
        get: operations["run_events_api_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Settings
         * @description The current graphite settings (recorded defaults on first run).
         */
        get: operations["read_settings_api_settings_get"];
        /**
         * Write Settings
         * @description Overwrite the whole settings document.
         */
        put: operations["write_settings_api_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Settings Route
         * @description Reset graphite's own settings to their recorded defaults.
         */
        post: operations["reset_settings_route_api_settings_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AcceptanceLedgerSummary
         * @description WOG1-F3 marked-provisional bridge: the ON-DISK
         *     `acceptance_ledger.json` (written by
         *     `acceptance.acceptance_ledger_bytes`) is a DIFFERENT shape than the
         *     in-memory `regolith.orchestrator.acceptance.AcceptanceOutcome`
         *     model it is rendered from (no `accepted_hashes` field on disk, and
         *     `accepted_deviations` replaces `deviations`) -- there is no
         *     regolith model that round-trips this file directly, so
         *     `AcceptanceOutcome.model_validate_json` fails against it. This is a
         *     graphite-local shape mirroring exactly what ships to disk, escalated
         *     to the lithos coordinator as a gap (a `LedgerDocument` model in
         *     `regolith.orchestrator.acceptance` would close it).
         */
        AcceptanceLedgerSummary: {
            /**
             * Accepted Deviations
             * @default []
             */
            accepted_deviations: components["schemas"]["AcceptedDeviation"][];
            /**
             * Cli Accepts Used
             * @default []
             */
            cli_accepts_used: string[];
            /**
             * Errors
             * @default []
             */
            errors: string[];
            /**
             * Refusals
             * @default []
             */
            refusals: string[];
        };
        /**
         * AcceptanceOutcome
         * @description The release gate's read of the ledger (WO-98).
         *
         *     ``accepted_hashes`` are the obligation content hashes an
         *     evidence-carrying, trust-floor-meeting, unexpired waiver accepted --
         *     the gate removes them from the refusing counts (kept DISTINCT as
         *     ``GateCounts.accepted_deviation``, never folded into ``discharged``).
         *     ``ledger_blocked`` is set when the ledger itself carries a hole that
         *     refuses independent of the results (a ``todo!``/``assume!`` that
         *     emitted no obligation of its own). ``refusals``/``errors`` are the
         *     human-readable reasons the gate reports.
         */
        AcceptanceOutcome: {
            /**
             * Accepted Hashes
             * @default []
             */
            accepted_hashes: string[];
            /**
             * Cli Accepts Used
             * @default []
             */
            cli_accepts_used: string[];
            /**
             * Deviations
             * @default []
             */
            deviations: components["schemas"]["Deviation"][];
            /**
             * Errors
             * @default []
             */
            errors: string[];
            /**
             * Ledger Blocked
             * @default false
             */
            ledger_blocked: boolean;
            /**
             * Refusals
             * @default []
             */
            refusals: string[];
        };
        /**
         * AcceptedDeviation
         * @description One row of `dist/acceptance_ledger.json`'s `accepted_deviations`
         *     array (WOG1-F3 below) -- field-for-field what
         *     `regolith.orchestrator.acceptance.acceptance_ledger_bytes` writes.
         */
        AcceptedDeviation: {
            /**
             * Accepted
             * @default []
             */
            accepted: string[];
            /** Basis */
            basis: string;
            /** Evidence */
            evidence?: string | null;
            /** Evidence Digest */
            evidence_digest?: string | null;
            /** Expires */
            expires?: string | null;
            /** Kind */
            kind: string;
            /**
             * Match Set
             * @default []
             */
            match_set: string[];
            /** Scope */
            scope?: string | null;
            /** Target */
            target: string;
        };
        /**
         * ArtifactEntry
         * @description One indexed file under a project's `dist/`: its content hash,
         *     a UI-facing relative path (display only, never used to serve),
         *     size, and guessed MIME type.
         */
        ArtifactEntry: {
            /** Content Hash */
            content_hash: string;
            /** Content Type */
            content_type: string;
            /** Relpath */
            relpath: string;
            /** Size */
            size: number;
        };
        /**
         * AuditIndex
         * @description The package-level audit index: total accounting + per-obligation rows.
         */
        AuditIndex: {
            /** Project */
            project: string;
            /** Rows */
            rows: components["schemas"]["AuditRow"][];
            summary: components["schemas"]["AuditSummary"];
        };
        /**
         * AuditRow
         * @description One obligation's disposition in the audit index (D221.2).
         *
         *     ``detail`` names the exact evidence: for a ``calc_sheet`` the sheet
         *     id; for an ``accepted_deviation`` the waiver target + its memo digest
         *     (cross-linking ``acceptance_ledger.json``, never duplicating it); for
         *     a ``deferred``/``violated`` row the named reason.
         */
        AuditRow: {
            /** Claim Name */
            claim_name: string;
            /** Content Hash */
            content_hash: string;
            /** Detail */
            detail: string;
            /**
             * Disposition
             * @enum {string}
             */
            disposition: "calc_sheet" | "accepted_deviation" | "deferred" | "violated";
            /** Subject Anchor */
            subject_anchor: string;
        };
        /**
         * AuditSummary
         * @description The audit index's obligation accounting (D221.2).
         *
         *     TWO honest denominators, both reported so they can never be confused:
         *
         *     * the CENSUS-shape counts (``discharged`` = results with no deferral;
         *       ``accepted_deviation`` = the number of UNIQUE accepted obligation
         *       content addresses -- exactly ``len(acceptance.accepted_hashes)``,
         *       the same value ``fleet._census_from_report`` records; ``violated``)
         *       so the audit index reconciles with ``fleet_census.json`` field for
         *       field via :meth:`census_row`;
         *     * the ROW partition (``discharged`` + ``accepted_rows`` + ``deferred``
         *       + ``violated`` == ``obligations``), because a calc sheet and an
         *       audit row are PER OBLIGATION and forall-expanded obligation
         *       instances legitimately share one content address -- so the number
         *       of accepted ROWS (:attr:`accepted_rows`) can exceed the number of
         *       unique accepted addresses (:attr:`accepted_deviation`). The row
         *       partition is the zero-unexplained property (:meth:`balanced`).
         */
        AuditSummary: {
            /** Accepted Deviation */
            accepted_deviation: number;
            /** Accepted Rows */
            accepted_rows: number;
            /** Deferred */
            deferred: number;
            /** Discharged */
            discharged: number;
            /** Obligations */
            obligations: number;
            /** Violated */
            violated: number;
        };
        /** Body_set_project_config_api_projects__project__config__key__put */
        Body_set_project_config_api_projects__project__config__key__put: {
            /**
             * Level
             * @enum {string}
             */
            level: "global" | "local";
            /** Value */
            value: string;
        };
        /** Body_start_project_run_api_projects__project__runs_post */
        Body_start_project_run_api_projects__project__runs_post: {
            /**
             * Args
             * @default []
             */
            args: string[];
            /**
             * Verb
             * @enum {string}
             */
            verb: "build" | "ship" | "test" | "optimize" | "check" | "preview";
        };
        /**
         * BuildReport
         * @description The outcome of one orchestrated build at a given tier.
         */
        BuildReport: {
            /**
             * @default {
             *       "accepted_hashes": [],
             *       "cli_accepts_used": [],
             *       "deviations": [],
             *       "errors": [],
             *       "ledger_blocked": false,
             *       "refusals": []
             *     }
             */
            acceptance: components["schemas"]["AcceptanceOutcome"];
            /**
             * @default {
             *       "hits": 0,
             *       "misses": 0
             *     }
             */
            cache_stats: components["schemas"]["CacheStats"];
            /**
             * Cost Estimates
             * @default []
             */
            cost_estimates: [
                string,
                string
            ][];
            /** Cost Profile */
            cost_profile?: string | null;
            /**
             * Cost Record Pins
             * @default []
             */
            cost_record_pins: [
                string,
                string
            ][];
            /**
             * Fluid Record Pins
             * @default []
             */
            fluid_record_pins: [
                string,
                string
            ][];
            /**
             * Frame Lock Rows
             * @default []
             */
            frame_lock_rows: components["schemas"]["LockRow"][];
            /**
             * Frame Record Pins
             * @default []
             */
            frame_record_pins: [
                string,
                string
            ][];
            /**
             * Loop Iterations
             * @default 0
             */
            loop_iterations: number;
            /**
             * Material Record Pins
             * @default []
             */
            material_record_pins: [
                string,
                string
            ][];
            /** Ok */
            ok: boolean;
            /**
             * Payload Json
             * @default
             */
            payload_json: string;
            /**
             * Plan Record Pins
             * @default []
             */
            plan_record_pins: [
                string,
                string
            ][];
            /**
             * Plugin Errors
             * @default []
             */
            plugin_errors: (components["schemas"]["DuplicateModelId"] | components["schemas"]["EntryPointRaised"] | components["schemas"]["MethodNamedKind"] | components["schemas"]["DuplicatePluginId"] | components["schemas"]["MalformedPluginManifest"] | components["schemas"]["PluginEntryPointRaised"])[];
            /**
             * Release Ok
             * @default true
             */
            release_ok: boolean;
            /**
             * Rendered
             * @default
             */
            rendered: string;
            /**
             * Results
             * @default []
             */
            results: components["schemas"]["ObligationResult"][];
            tier: components["schemas"]["BuildTier"];
            /**
             * Unresolved
             * @default []
             */
            unresolved: components["schemas"]["ObligationResult"][];
        };
        /**
         * BuildTier
         * @description The build ladder, ordered by how much work the tier performs.
         *
         *     The integer value IS the order (``IntEnum``): higher tiers include the
         *     lower tiers' work, so ``BuildTier.RELEASE > BuildTier.CHECK`` and
         *     :meth:`includes` are the same fact.
         * @enum {integer}
         */
        BuildTier: 0 | 1 | 2 | 3;
        /**
         * CacheStats
         * @description Hit/miss counters for one orchestration run (observability).
         */
        CacheStats: {
            /**
             * Hits
             * @default 0
             */
            hits: number;
            /**
             * Misses
             * @default 0
             */
            misses: number;
        };
        /**
         * CalcInput
         * @description One input to a calc sheet's obligation, with its provenance pin.
         *
         *     ``value`` is the datum as written (unit-carrying text is kept
         *     verbatim -- the source is the truth, never re-normalized); ``pin`` is
         *     the content address for a ``record_ref`` (else empty). ``source`` is
         *     the human-readable origin (the record name, the literal expression,
         *     or the derived value-source text).
         */
        CalcInput: {
            /** Name */
            name: string;
            /**
             * Pin
             * @default
             */
            pin: string;
            /**
             * Provenance
             * @enum {string}
             */
            provenance: "record_ref" | "declared_literal" | "derived" | "unresolved";
            /**
             * Source
             * @default
             */
            source: string;
            /** Value */
            value: string;
        };
        /**
         * CalcSheet
         * @description One discharged obligation's calc sheet (D221.1).
         */
        CalcSheet: {
            /** Attestation */
            attestation: string;
            chain: components["schemas"]["EvidenceChain"];
            /** Citation */
            citation: string;
            /** Claim Name */
            claim_name: string;
            /** Claim Text */
            claim_text: string;
            /** Inputs */
            inputs: components["schemas"]["CalcInput"][];
            /** Margin */
            margin: string;
            /** Model Id */
            model_id: string;
            /** Model Version */
            model_version: string;
            /** Sheet Id */
            sheet_id: string;
            /** Solver */
            solver: string;
            /** Subject Anchor */
            subject_anchor: string;
            /** Subject Ref */
            subject_ref: string;
            /** Tier */
            tier: string;
            /** Value */
            value: string;
            /** Verdict */
            verdict: string;
        };
        /**
         * ConfigEntry
         * @description One `regolith config` key: its effective value and the
         *     where-attribution level that won it (04.1 "ANY FORM/CONFIG FIELD"
         *     floor: source attribution is mandatory, never omitted).
         */
        ConfigEntry: {
            /** Key */
            key: string;
            /** Source */
            source: string;
            /** Value */
            value: string;
        };
        /**
         * ConfigKeyDefault
         * @description One registered key's declared default + doc, for the "reset to
         *     default" affordance (04.1). Neither `regolith config list` nor
         *     `where` prints the default -- only the CURRENT winning value and
         *     its source (WOG1-F5's `--json` gap compounds this: there is no
         *     stable stdout line to parse for "the default" either).
         *
         *     WOG6-F1 (escalation, placeholder): this reads `regolith.config.
         *     registered_keys()` directly (a Python import of the installed
         *     `regolith` wheel), not a CLI subprocess -- the ONE exception to
         *     this module's "always shell out" rule. It is a read of static,
         *     compiled-in registry metadata (key/kind/default/doc), never
         *     project state and never a write, so it does not violate "edits
         *     write through the real CLI" (that doctrine governs mutation, not
         *     read-only introspection of a constant table). Recorded for the
         *     lithos coordinator: a `regolith config list --json` (or a
         *     `--show-default` flag) would let this module drop the import and
         *     go through the CLI uniformly like every other read here.
         */
        ConfigKeyDefault: {
            /** Default */
            default: string | number | boolean;
            /** Doc */
            doc: string;
            /** Key */
            key: string;
            /** Kind */
            kind: string;
        };
        /**
         * Coverage
         * @description Structured coverage (D95, sec. 8.2): per-axis coverage plus the conservative scalar collapse kept for margin notes and old consumers -- `fraction` must never overstate what `axes` states. `Evidence`/`SolverResponse` carry this instead of a bare float.
         */
        Coverage: {
            /**
             * Axes
             * @description The per-axis coverage record (empty for a closed-form/full claim).
             */
            axes: components["schemas"]["CoverageAxis"][];
            /**
             * Fraction Bits
             * @description The conservative scalar collapse (`1.0` = full), as `f64` bits.
             */
            fraction_bits: number;
        };
        /**
         * CoverageAxis
         * @description One axis of structured coverage: the swept variable, its domain, and the method used to cover it (D95, sec. 8.2).
         */
        CoverageAxis: {
            /**
             * Axis
             * @description The swept axis name.
             */
            axis: string;
            /**
             * Domain
             * @description The axis's domain (continuous or discrete).
             */
            domain: components["schemas"]["CoverageDomain1"] | components["schemas"]["CoverageDomain2"];
            /**
             * Method
             * @description The method used to cover this axis.
             */
            method: components["schemas"]["CoverageMethod1"] | components["schemas"]["CoverageMethod2"] | components["schemas"]["CoverageMethod3"] | components["schemas"]["CoverageMethod4"] | components["schemas"]["CoverageMethod5"] | components["schemas"]["CoverageMethod6"];
        };
        /**
         * CoverageDomain1
         * @description A continuous domain, as text (e.g. `"[300K, 400K]"`).
         */
        CoverageDomain1: {
            /** Interval */
            interval: string;
        };
        /**
         * CoverageDomain2
         * @description A discrete domain (valve line-ups, failure states, ...).
         */
        CoverageDomain2: {
            values: components["schemas"]["Values"];
        };
        /**
         * CoverageMethod1
         * @description Corner-only sampling.
         * @enum {string}
         */
        CoverageMethod1: "corners";
        /**
         * CoverageMethod2
         * @description A grid with per-axis resolution `k` (multi-dim: `grid(k x m)`, the G29 demand).
         */
        CoverageMethod2: {
            grid: components["schemas"]["Grid"];
        };
        /**
         * CoverageMethod3
         * @description Every discrete value was enumerated.
         * @enum {string}
         */
        CoverageMethod3: "enumerated";
        /**
         * CoverageMethod4
         * @description A closed-form analytic bound covers the whole domain.
         * @enum {string}
         */
        CoverageMethod4: "analytic";
        /**
         * CoverageMethod5
         * @description Declared monotonicity lets the worst corner stand for the domain.
         * @enum {string}
         */
        CoverageMethod5: "monotone";
        /**
         * CoverageMethod6
         * @description WO-33 D98: the axis is DECLARED (a `compute` claim's index domain) but not yet resolved by any model -- the honest pre-discharge state of a [`crate::field::FieldDatum`]'s axis (`payload: null`). Never appears once evidence has landed; a discharging model replaces it with the method it actually used.
         * @enum {string}
         */
        CoverageMethod6: "undischarged";
        /**
         * Deferral
         * @description An obligation the orchestrator could not lower to a numeric request.
         *
         *     Honest, greppable, and release-gated: a deferral is neither a pass nor
         *     a violation -- it says "no numeric obligation was formed here" and the
         *     release gate (INV-24) treats it as unresolved.
         */
        Deferral: {
            /** Detail */
            detail: string;
            /** Reason */
            reason: string;
        };
        /**
         * Deviation
         * @description One accepted deviation for the gate summary + acceptance ledger.
         *
         *     Mirrors the source waiver's declared surface (target/scope/basis/
         *     evidence/kind/match set/expiry) plus the obligation content hashes it
         *     actually accepted this build -- the audit row `ship` writes into
         *     ``acceptance_ledger.json`` and `ship --explain` lists.
         */
        Deviation: {
            /** Accepted */
            accepted: string[];
            /** Basis */
            basis: string;
            /** Evidence */
            evidence: string | null;
            /**
             * Evidence Digest
             * @default
             */
            evidence_digest: string;
            /** Expires */
            expires: string | null;
            /** Kind */
            kind: string;
            /** Match Set */
            match_set: string[];
            /** Scope */
            scope: string | null;
            /** Target */
            target: string;
        };
        /**
         * DuplicateModelId
         * @description A pack declared a model id something already registered (D-B).
         *
         *     D94: the registry key is ``(claim_kind, model_id)`` -- one model MAY
         *     register under two DIFFERENT kinds legally, so this is a duplicate
         *     only when the SAME kind already has that id. Two models sharing one
         *     id under ONE kind would make selection ambiguous; the whole pack is
         *     skipped (no partial load) and named.
         */
        DuplicateModelId: {
            /** Model Id */
            model_id: string;
            /** Pack */
            pack: string;
        };
        /**
         * DuplicatePluginId
         * @description Two plugins of the same kind declared the same id (AD-26: ids are
         *     globally unique per kind; the second is skipped, named by its
         *     source entry point).
         */
        DuplicatePluginId: {
            /** Plugin Id */
            plugin_id: string;
            /** Source */
            source: string;
        };
        /**
         * EntryPointRaised
         * @description A pack's ``register_fn`` callable raised while composing (not while
         *     the entry point resolved to a manifest -- that failure is a generic
         *     ``regolith.plugins.PluginEntryPointRaised``, folded into ``skipped``
         *     the same way). Third-party pack code is a plugin boundary: its
         *     exceptions are OUR recoverable data (the pack is skipped loudly),
         *     never a crashed build.
         */
        EntryPointRaised: {
            /** Message */
            message: string;
            /** Pack */
            pack: string;
        };
        /**
         * Evidence
         * @description The evidence produced by discharging one obligation.
         */
        Evidence: {
            /**
             * Cost
             * @description Relative cost incurred.
             */
            cost: number;
            /** @description Structured per-axis coverage (D95, sec. 8.2); `Coverage::full()` for a closed-form/full claim. */
            coverage: components["schemas"]["Coverage"];
            /**
             * Eps Bits
             * @description The model error `eps`'s bits.
             */
            eps_bits: number;
            /**
             * Hash
             * @description Content hash of this evidence (cache key component).
             */
            hash: string;
            /**
             * Margin Bits
             * @description The margin after error (`limit - (value + eps)`)'s bits.
             */
            margin_bits: number;
            /**
             * Model Id
             * @description The discharge model id that produced this.
             */
            model_id: string;
            /**
             * Status
             * @description The discharge status.
             */
            status: components["schemas"]["Status1"] | components["schemas"]["Status2"] | components["schemas"]["Status3"];
            /**
             * Value Bits
             * @description The computed value's bits (f64 as bits for exact serialization).
             */
            value_bits: number;
        };
        /**
         * EvidenceChain
         * @description The content-hash chain proving a calc sheet's derivation (D221.1).
         *
         *     ``sheet_digest`` is the producer-local blake3 of the sheet's own
         *     canonical bytes (``local-blake3:`` tagged, charter 38 sec. 1.4);
         *     ``evidence_hash`` / ``subject_ref`` / ``record_pins`` are the
         *     CANONICAL Rust content addresses off the payload (untagged). A
         *     reviewer follows sheet -> evidence -> payload -> sources without
         *     trusting anything but the shipped bytes.
         */
        EvidenceChain: {
            /** Evidence Hash */
            evidence_hash: string;
            /**
             * Payload Refs
             * @default []
             */
            payload_refs: string[];
            /**
             * Record Pins
             * @default []
             */
            record_pins: string[];
            /** Sheet Digest */
            sheet_digest: string;
            /** Subject Ref */
            subject_ref: string;
        };
        /**
         * GateCounts
         * @description `dist/gate_summary.json`'s `counts` object verbatim (WOG3-F1
         *     marked-provisional bridge, same posture as `ManifestSummary`/
         *     `AcceptanceLedgerSummary`: no dedicated regolith model for this
         *     on-disk shape exists yet in the public surface).
         */
        GateCounts: {
            /** Accepted Deviation */
            accepted_deviation: number;
            /** Below Trust Floor */
            below_trust_floor: number;
            /** Indeterminate */
            indeterminate: number;
            /** Ledger Blocked */
            ledger_blocked: boolean;
            /** Violated */
            violated: number;
        };
        /**
         * GateSummary
         * @description `dist/gate_summary.json` -> the release-gate summary panel (04.1
         *     project-view release-gate deliverable): tier + ok + release_ok +
         *     per-kind counts, read verbatim, never recomputed (charter 3.2).
         */
        GateSummary: {
            counts: components["schemas"]["GateCounts"];
            /** Ok */
            ok: boolean;
            /** Release Ok */
            release_ok: boolean;
            /** Tier */
            tier: string;
        };
        /**
         * GraphiteSettings
         * @description graphite's own preferences: a default project root to land on at
         *     startup and a run verbosity passthrough for driven CLI invocations.
         *     Never a regolith config key (that precedence ladder is a different
         *     doctrine, D163/D164 -- this is graphite-local UI state).
         */
        GraphiteSettings: {
            /**
             * Default Project Root
             * @default
             */
            default_project_root: string;
            /**
             * Run Verbosity
             * @default normal
             * @enum {string}
             */
            run_verbosity: "quiet" | "normal" | "verbose";
        };
        /** Grid */
        Grid: {
            /**
             * K
             * @description Per-axis grid resolution.
             */
            k: components["schemas"]["KItem"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Invalid
         * @description A present-but-unverifiable attestation: INDETERMINATE, never a verdict.
         */
        Invalid: {
            /** Detail */
            detail: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "invalid";
            /**
             * Reason
             * @enum {string}
             */
            reason: "bad_signature" | "unknown_key" | "algorithm_mismatch";
        };
        /** KItem */
        KItem: number;
        /**
         * LockRow
         * @description One resolved pin: a slot, its value, and its resolving cause.
         *
         *     Renders as regolith/03 sec. 2's shape::
         *
         *         flange.radius = 2.4mm         cause: dfm(sheet.min_bend_radius)
         */
        LockRow: {
            /** Cause */
            cause: string;
            /** Policy Note */
            policy_note?: string | null;
            /** Slot */
            slot: string;
            /** Value */
            value: string;
        };
        /**
         * LockSection
         * @description A per-target or per-variant section of rows plus record pins.
         */
        LockSection: {
            /** Name */
            name: string;
            /**
             * Record Pins
             * @default []
             */
            record_pins: [
                string,
                string
            ][];
            /**
             * Rows
             * @default []
             */
            rows: components["schemas"]["LockRow"][];
        };
        /**
         * Lockfile
         * @description The full lockfile: tool/registry versions plus ordered sections.
         */
        Lockfile: {
            /**
             * Sections
             * @default []
             */
            sections: components["schemas"]["LockSection"][];
            /** Tool Version */
            tool_version: string;
        };
        /**
         * MalformedPluginManifest
         * @description An entry point's target was not a :class:`PluginManifest`.
         */
        MalformedPluginManifest: {
            /** Message */
            message: string;
            /** Source */
            source: string;
        };
        /**
         * ManifestSummary
         * @description WOG1-F2 marked-provisional bridge: the ship package
         *     `manifest.json` shape trimmed to what the UI needs, pending a real
         *     regolith model (no dedicated one exists in the public surface --
         *     the ship backend assembles this dict ad hoc). Extra keys in the
         *     real file are read but not exposed here; `raw` carries the full
         *     parsed dict for a UI "raw JSON toggle" (04.1 detail-view floor).
         */
        ManifestSummary: {
            /** Design Hash */
            design_hash?: string | null;
            /** Raw */
            raw: {
                [key: string]: unknown;
            };
            /** Signed */
            signed: boolean;
        };
        /**
         * MethodNamedKind
         * @description A pack declared a claim kind naming a method/tool, not WHAT is
         *     claimed (D94, sec. 8.1: `mech.fea.static_stress` was a bootstrap
         *     error). The whole pack is skipped, naming the offending word.
         */
        MethodNamedKind: {
            /** Claim Kind */
            claim_kind: string;
            /** Pack */
            pack: string;
            /** Word */
            word: string;
        };
        /**
         * ObligationGroup
         * @description One `group=` bucket: the key value (a disposition or a family)
         *     plus its member rows, in source order.
         */
        ObligationGroup: {
            /** Key */
            key: string;
            /** Rows */
            rows: components["schemas"]["AuditRow"][];
        };
        /**
         * ObligationResult
         * @description The outcome of routing one obligation through the harness.
         *
         *     Exactly one of ``evidence`` / ``deferral`` is set: ``evidence`` when a
         *     model (or the total no-model path) produced a verdict, ``deferral``
         *     when the obligation could not even be lowered to a numeric request.
         *     ``from_cache`` records whether this was a cache hit (observability).
         */
        ObligationResult: {
            /** Attestation */
            attestation?: components["schemas"]["Valid"] | components["schemas"]["Unsigned"] | components["schemas"]["Invalid"];
            /**
             * Content Hash
             * @default
             */
            content_hash: string;
            deferral?: components["schemas"]["Deferral"] | null;
            evidence?: components["schemas"]["Evidence"] | null;
            /**
             * From Cache
             * @default false
             */
            from_cache: boolean;
            /** Key */
            key: string;
            /** Subject Ref */
            subject_ref: string;
            /** Trust Floor */
            trust_floor?: string | null;
        };
        /**
         * ObligationsResponse
         * @description The obligations listing: the real `AuditSummary` (unmodified)
         *     plus either a flat `rows` array or, when `group` is given,
         *     `groups` -- never both, so a client always knows which shape to
         *     render.
         */
        ObligationsResponse: {
            /** Groups */
            groups?: components["schemas"]["ObligationGroup"][] | null;
            /** Rows */
            rows?: components["schemas"]["AuditRow"][] | null;
            summary: components["schemas"]["AuditSummary"];
        };
        /**
         * PluginEntryPointRaised
         * @description An entry point raised while loading (third-party code is a plugin
         *     boundary: its exceptions are our recoverable data, never a crashed
         *     discovery pass).
         */
        PluginEntryPointRaised: {
            /** Message */
            message: string;
            /** Source */
            source: string;
        };
        /**
         * ProjectHealth
         * @description The title-block verdict summary for one project.
         */
        ProjectHealth: {
            obligation_summary: components["schemas"]["AuditSummary"];
            /** Release Ok */
            release_ok: boolean;
        };
        /**
         * ProjectInfo
         * @description One discovered project: its manifest identity plus which report
         *     artifacts already exist on disk (a fresh project has none of
         *     them -- that is not an error, just an empty-state signal for the
         *     UI's companion-audit empty state, 04.1).
         */
        ProjectInfo: {
            /**
             * Build Report Stale
             * @default false
             */
            build_report_stale: boolean;
            /** Has Build Report */
            has_build_report: boolean;
            /** Has Dist */
            has_dist: boolean;
            /** Has Lockfile */
            has_lockfile: boolean;
            /** Manifest Path */
            manifest_path: string;
            /** Name */
            name: string;
            /** Root */
            root: string;
            /** Version */
            version: string;
        };
        /**
         * RealizedInput
         * @description One caller-resolved realized-domain IR (WO-42 deliverable 3,
         *     AD-25/D128): the orchestrator has already resolved ``digest`` against
         *     the WO-30 content store into ``payload_bytes`` -- this facade does no
         *     IO of its own, only marshals the resolved content across the ONE
         *     coarse FFI crossing (AD-4). ``kind`` is a D96 payload kind (e.g.
         *     ``"geometry.realized"``); ``subject`` is the part/block the IR was
         *     realized for (matched against a flownet edge's ``from=`` ref).
         */
        RealizedInput: {
            /** Digest */
            digest: string;
            /** Kind */
            kind: string;
            /** Payload Bytes */
            payload_bytes: string;
            /** Subject */
            subject: string;
        };
        /**
         * RunRecord
         * @description One persisted run: identity, the verb driven, its live/final
         *     status, timestamps, and the project root it ran against. The log
         *     file and (for `--json` verbs) the stdout JSON blob live alongside
         *     it as sibling files (`<id>.log`, `<id>.stdout.json`), not inlined
         *     here -- this record is the cheap-to-list summary row.
         */
        RunRecord: {
            /** Args */
            args: string[];
            /** Exit Code */
            exit_code?: number | null;
            /** Finished At */
            finished_at?: string | null;
            /** Project Root */
            project_root: string;
            /** Run Id */
            run_id: string;
            /** Started At */
            started_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "ok" | "failed";
            /**
             * Verb
             * @enum {string}
             */
            verb: "build" | "ship" | "test" | "optimize" | "check" | "preview";
        };
        /**
         * StagedBuildReport
         * @description The outcome of WO-42 deliverable 5's staged build loop (AD-25/D128):
         *     lower -> realize (producing new realized-domain IRs) -> re-lower with
         *     them, to a fixed point.
         *
         *     ``final`` is the last :class:`BuildReport` (the fixed-point build --
         *     the one whose ``payload_json`` no longer names a realizable pending
         *     subject). ``iterations`` counts how many core ``check``/``compile``
         *     passes ran (always >= 1: the loop always runs at least once, even
         *     with no ``feature_programs`` supplied). ``realized_inputs`` is every
         *     realized-domain IR supplied to the FINAL pass, and ``lock_rows`` are
         *     their INV-21 lockfile rows (:func:`realized_lock_rows`).
         */
        StagedBuildReport: {
            final: components["schemas"]["BuildReport"];
            /** Iterations */
            iterations: number;
            /**
             * Lock Rows
             * @default []
             */
            lock_rows: components["schemas"]["LockRow"][];
            /**
             * Realized Inputs
             * @default []
             */
            realized_inputs: components["schemas"]["RealizedInput"][];
        };
        /**
         * Status1
         * @description The claim holds with margin after the model's error.
         * @enum {string}
         */
        Status1: "discharged";
        /**
         * Status2
         * @description The claim provably fails at its worst corner.
         * @enum {string}
         */
        Status2: "violated";
        /**
         * Status3
         * @description No adequate model, coverage, or trust; neither proven nor disproven (distinct from violated).
         * @enum {string}
         */
        Status3: "indeterminate";
        /**
         * TrustTier
         * @description The total order of evidence trust (regolith/11 sec. 7).
         *
         *     The integer value IS the rank, so ``TrustTier.CERTIFIED > TrustTier.
         *     TESTED`` and floor comparison are the same fact (INV-14 totality).
         * @enum {integer}
         */
        TrustTier: 0 | 1 | 2;
        /**
         * Unsigned
         * @description No attestation present -- the honest ``community`` tier, not an error.
         */
        Unsigned: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "unsigned";
        };
        /**
         * Valid
         * @description A verified attestation: the evidence earns ``tier`` from a trusted key.
         */
        Valid: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "valid";
            tier: components["schemas"]["TrustTier"];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Values */
        Values: {
            /**
             * Values
             * @description The enumerated values, as text.
             */
            values: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_config_schema_api_config_schema_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigKeyDefault"][];
                };
            };
        };
    };
    ping_api_ping_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_projects_api_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectInfo"][];
                };
            };
        };
    };
    get_project_api_projects__project__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_acceptance_ledger_api_projects__project__acceptance_ledger_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptanceLedgerSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_project_artifacts_api_projects__project__artifacts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fetch_project_artifact_api_projects__project__artifacts__content_hash__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project: string;
                content_hash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_build_report_api_projects__project__build_report_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StagedBuildReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_audit_index_api_projects__project__calc_audit_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditIndex"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_calc_sheets_api_projects__project__calc_sheets_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalcSheet"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_project_config_api_projects__project__config_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_config_api_projects__project__config__key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project: string;
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_project_config_api_projects__project__config__key__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project: string;
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_set_project_config_api_projects__project__config__key__put"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_doctor_api_projects__project__doctor_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_gate_summary_api_projects__project__gate_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GateSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_health_api_projects__project__health_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectHealth"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lockfile_api_projects__project__lockfile_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lockfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_manifest_api_projects__project__manifest_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManifestSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_obligations_api_projects__project__obligations_get: {
        parameters: {
            query?: {
                /** @description disposition to keep, e.g. 'violated' */
                filter?: string | null;
                /** @description 'disposition' or 'family' */
                group?: string | null;
            };
            header?: never;
            path: {
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObligationsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_project_runs_api_projects__project__runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_project_run_api_projects__project__runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_start_project_run_api_projects__project__runs_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_detail_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_events_api_runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphiteSettings"];
                };
            };
        };
    };
    write_settings_api_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GraphiteSettings"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphiteSettings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_settings_route_api_settings_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphiteSettings"];
                };
            };
        };
    };
}
