// Generator for the token law (spec 03.4): src/tokens/tokens.ts is the ONLY
// hand-edited source; this script emits the two mirrors below. `make
// frontend-check` runs it and diffs against the committed output (drift
// check) -- CI fails if a human edited a generated file directly instead of
// tokens.ts.
//
// Run: npm run build:tokens

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { tokens } from '../src/tokens/tokens.ts';

const here = path.dirname(fileURLToPath(import.meta.url));
const cssOut = path.join(here, '../src/tokens/tokens.css');
const pyOut = path.join(here, '../../graphite/tui/tokens.py');

function flattenToVars(obj: unknown, prefix: string[], theme: string | null, out: string[]): void {
  if (obj !== null && typeof obj === 'object' && !Array.isArray(obj)) {
    for (const [key, value] of Object.entries(obj as Record<string, unknown>)) {
      flattenToVars(value, [...prefix, toKebab(key)], theme, out);
    }
    return;
  }
  const name = `--graphite-${prefix.join('-')}`;
  out.push(`  ${name}: ${String(obj)};`);
}

function buildCss(): string {
  const lines: string[] = [];
  lines.push('/* GENERATED by scripts/build-tokens.ts -- do not hand-edit. */');
  lines.push('/* Source of truth: src/tokens/tokens.ts */');
  lines.push(':root {');
  for (const key of [
    'space',
    'radius',
    'fontSize',
    'lineHeight',
    'fontFamily',
    'letterSpacing',
    'borderWidth',
    'motion',
  ] as const) {
    flattenToVars(tokens[key], [toKebab(key)], null, lines);
  }
  lines.push('}');
  lines.push('');
  lines.push(':root[data-theme="dark"] {');
  flattenToVars(tokens.color.dark, ['color'], 'dark', lines);
  lines.push('}');
  lines.push('');
  lines.push(':root[data-theme="light"] {');
  flattenToVars(tokens.color.light, ['color'], 'light', lines);
  lines.push('}');
  lines.push('');
  return lines.join('\n') + '\n';
}

function toKebab(s: string): string {
  return s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
}

function pyLiteral(v: unknown): string {
  return `"${String(v)}"`;
}

function buildPy(): string {
  const lines: string[] = [];
  lines.push('"""GENERATED by frontend/scripts/build-tokens.ts -- do not hand-edit.');
  lines.push('');
  lines.push('Mirrors frontend/src/tokens/tokens.ts (the one token source, spec 03.4)');
  lines.push('for the textual TUI so both renderers share one design vocabulary.');
  lines.push('"""');
  lines.push('');
  lines.push('from __future__ import annotations');
  lines.push('');
  lines.push('SPACE: dict[str, str] = {');
  for (const [k, v] of Object.entries(tokens.space)) {
    lines.push(`    "${k}": ${pyLiteral(v)},`);
  }
  lines.push('}');
  lines.push('');
  lines.push('RADIUS: dict[str, str] = {');
  for (const [k, v] of Object.entries(tokens.radius)) {
    lines.push(`    "${k}": ${pyLiteral(v)},`);
  }
  lines.push('}');
  lines.push('');
  lines.push('FONT_SIZE: dict[str, str] = {');
  for (const [k, v] of Object.entries(tokens.fontSize)) {
    lines.push(`    "${k}": ${pyLiteral(v)},`);
  }
  lines.push('}');
  lines.push('');
  for (const theme of ['dark', 'light'] as const) {
    const palette = tokens.color[theme];
    lines.push(`COLOR_${theme.toUpperCase()}: dict[str, str] = {`);
    for (const [k, v] of Object.entries(palette)) {
      if (typeof v === 'string') {
        lines.push(`    "${k}": ${pyLiteral(v)},`);
      } else {
        for (const [vk, vv] of Object.entries(v as Record<string, string>)) {
          lines.push(`    "verdict.${vk}": ${pyLiteral(vv)},`);
        }
      }
    }
    lines.push('}');
    lines.push('');
  }
  return lines.join('\n');
}

writeFileSync(cssOut, buildCss());
writeFileSync(pyOut, buildPy());
console.log(`wrote ${cssOut}`);
console.log(`wrote ${pyOut}`);
